### ISSUE TITLE
Version 1.0.1 of add-on not in official Kodi repository

### ISSUE THREAD

**Issue by paulvt** [realcopacetic/script.copacetic.helper#2]
Hi!

Version 1.0.1 of this add-on is missing from the official Kodi repository (for Nexus) and thus prevents the installation of the Copacetic skin version 1.0.1 that is in the official Kodi repository.

**Comment by realcopacetic** [comment]
Yep I'm aware. I submitted them both at the same time thinking the skin would be the longest approval process because it's the most code. But it was very quick. I've raised this on GitHub with team kodi do hopefully they will either approve the addon or remove the skin soon. In the meantime you can install the addon from my repo instead of your want to try the skin.
